CREATE TABLE comments (
  commentID INT AUTO_INCREMENT PRIMARY KEY,
  postID INT,
  userID INT,
  comment TEXT,
  commentDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (postID) REFERENCES posts(postID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
  INDEX (postID),
  INDEX (userID)
);